specVersion: 0.2.0
name: moonbeam_transactions
version: 0.0.4
description: This SubQuery project can be use as a starting point for Moonbeam network
repository: 'https://github.com/subquery/moonbeam-subql-starters'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://moonriver.api.onfinality.io/public-ws'
  genesisHash: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b'
  dictionary: 'https://api.subquery.network/sq/subquery/moonriver-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 2260800
    mapping:
      file: ./dist/index.js
      handlers:
        # - handler: handleTransfer
        #   kind: substrate/EventHandler
        #   filter:
        #     module: balances
        #     method: Transfer
        - handler: handleProxyAnnounced
          kind: substrate/EventHandler
          filter:
            module: proxy
            method: Announced
