specVersion: 0.2.0
name: moonbeam_transactions
version: 0.0.4
description: Track Moonbeam balance transfers
repository: 'https://github.com/gilmouta/moonbase_txs_subquery/'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://moonbeam.api.onfinality.io/public-ws'
  genesisHash: '0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d'
  dictionary: 'https://api.subquery.network/sq/subquery/moonbeam-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1000000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
