specVersion: 0.2.0
name: moonbeam_transactions
version: 0.0.4
description: Track Moonbeam balance transfers
repository: 'https://github.com/gilmouta/moonbase_txs_subquery/'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://moonriver.api.onfinality.io/public-ws'
  genesisHash: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b'
  dictionary: 'https://api.subquery.network/sq/subquery/moonriver-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1800000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
