specVersion: 0.2.0
name: moonbeam_transactions
version: 0.0.4
description: This SubQuery project can be use as a starting point for Moonbeam network
repository: 'https://github.com/subquery/moonbeam-subql-starters'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://frag-moonbase-alpha-ps-rpc-ws.g.moonbase.moonbeam.network'
  genesisHash: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527'
  dictionary: 'https://api.subquery.network/sq/subquery/moonbase-alpha-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 0
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
